language: python
addons:
  firefox: "45.4.0esr"
python:
  - "2.7"

services:
  - mysql

env:
  -DJANGO=1.11 DB=mysql

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database test;' -u root

script:
  - python manage.py test