# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-05 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperwork', '0002_deadline_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepdeadline',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_deadlines', to='paperwork.Deliverable'),
        ),
    ]
