# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperwork', '0003_auto_20180305_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='duration',
            field=models.IntegerField(choices=[(1, b'calendar_day'), (2, b'business_day')], default=1),
            preserve_default=False,
        ),
    ]
