# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperwork', '0004_deadline_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfoTypeSignature',
            fields=[
                ('clientinfotype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paperwork.ClientInfoType')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperwork.Deliverable')),
            ],
            bases=('paperwork.clientinfotype',),
        ),
        migrations.AlterField(
            model_name='clientinfodate',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
