# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperwork', '0005_auto_20180308_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDeadline',
            fields=[
                ('deadline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paperwork.Deadline')),
                ('relative_info_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperwork.ClientInfoTypeSignature')),
            ],
            bases=('paperwork.deadline',),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='review',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paperwork.ReviewDeadline'),
        ),
    ]
