# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperwork', '0006_auto_20180309_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperwork.Client')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperwork.Deliverable')),
            ],
        ),
    ]
